services:
  java:
    build:
      context: ./docker/java
    command: sh ./gradlew build --continuous # 自動ビルド実行
    container_name: spring_java
    tty: true
    working_dir: /app
    volumes:
      - ./spring:/app
    ports:
      - 8080:8080 # 通常実行用
      - 5050:5050 # デバッグ用
    depends_on:
      - mysql
  mysql:
    build: ./docker/mysql
    container_name: spring_mysql
    env_file:
      - ./docker/mysql/db.env # MySQL設定ファイル
    volumes:
      - ./docker/mysql/data:/var/lib/mysql # 実データの永続化
      - ./docker/mysql/log:/var/log/mysql # logの永続化
    ports:
      - 3306:3306
  dbclient:
    image: phpmyadmin/phpmyadmin
    container_name: spring_phpmyadmin
    environment:
      - PMA_ARBITRARY=1 # 任意のサーバーへの接続を許可
      - PMA_HOST=mysql # 接続先ホスト名　ここではdbサーバーのコンテナ名を指定
      - PMA_USER=dev_usr # MySQLの設定と合わせておく
      - PMA_PASSWORD=dev_usr_pass # MySQLの設定と合わせておく
    links:
     - mysql
    ports:
      - 4200:80
    volumes:
      - ./docker/dbclient/sessions:/sessions
    depends_on:
      - mysql # 「mysql」の後で起動
